export const SPEECH_LANGUAGE_OPTIONS = [
  { value: "", key: "auto", defaultLabel: "Detect automatically" },
  { value: "en", key: "en", defaultLabel: "English" },
  { value: "ru", key: "ru", defaultLabel: "Russian" },
  { value: "uk", key: "uk", defaultLabel: "Ukrainian" },
  { value: "de", key: "de", defaultLabel: "German" },
  { value: "es", key: "es", defaultLabel: "Spanish" },
  { value: "fr", key: "fr", defaultLabel: "French" },
  { value: "pt", key: "pt", defaultLabel: "Portuguese" },
  { value: "pl", key: "pl", defaultLabel: "Polish" },
  { value: "it", key: "it", defaultLabel: "Italian" },
  { value: "nl", key: "nl", defaultLabel: "Dutch" },
  { value: "tr", key: "tr", defaultLabel: "Turkish" },
  { value: "ar", key: "ar", defaultLabel: "Arabic" },
  { value: "zh", key: "zh", defaultLabel: "Chinese" },
  { value: "ja", key: "ja", defaultLabel: "Japanese" },
  { value: "ko", key: "ko", defaultLabel: "Korean" },
  { value: "hi", key: "hi", defaultLabel: "Hindi" },
] as const;
